#!/usr/bin/env bash


############################################################################################

RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`

SOURCE_DIR="$( cd "$(dirname "$0" 2>/dev/null)" >/dev/null 2>&1 ; pwd -P )"

############################################################################################

# remove existing symbolic links named .bash_aliases* from home directory
for FILE_PATH in $(find ~/ -maxdepth 1 -type l -name '.bash_aliases*' 2> /dev/null); do
	FILE=$(basename $FILE_PATH)
	# if symbolic link exists, then remove it
	if [ -L ~/$FILE ]; then
		echo "${RED}removing${RESET} symbolic link: ~/$FILE"
		rm ~/$FILE
	fi
done;

# remove existing symbolic links which are not named .bash_aliases*
for FILE_PATH in $(find $SOURCE_DIR/home -maxdepth 1 -type f -name '.*' 2> /dev/null); do
	FILE=$(basename $FILE_PATH)
	# if symbolic link exists, then remove it
	if [ -L ~/$FILE ]; then
		echo "${RED}removing${RESET} symbolic link: ~/$FILE"
		rm ~/$FILE
	fi
done;

# if file doesn't exist create new symbolic link
for FILE_PATH in $(find $SOURCE_DIR/home -maxdepth 1 -type f -name '.*' 2> /dev/null); do
	FILE=$(basename $FILE_PATH)
	if [ ! -f ~/$FILE ]; then
		echo "${GREEN}creating${RESET} symbolic link: ~/$FILE"
		ln -s $FILE_PATH ~/$FILE
	fi
done;
