#!/usr/bin/env bash


CUR_DIR="$( cd "$(dirname "$0" 2>/dev/null)" >/dev/null 2>&1 ; pwd -P )"

cd ~

for FILE_PATH in $(find $CUR_DIR -maxdepth 1 -type f -name '.*' 2> /dev/null); do
	FILE=$(basename $FILE_PATH)
	# if symbolic link exists, then remove it before
	if [ -L ~/$FILE ]; then
		echo "Removing symbolic link: ~/$FILE"
		rm ~/$FILE
	fi
	if [ ! -f ~/$FILE ]; then
		echo "Creating symbolic link: ~/$FILE"
		ln -s $FILE_PATH ~/$FILE
	fi
done;

cd -

